import { defineStore } from 'pinia';

export const useOrderStore = defineStore('order', {
  state: () => ({
    formConfig: {
      createAccount: false,
      differentAddress: false,
      shippingMethods: [],
      paymentMethods: [],
      shoppingCartDetails: [],
      isCaptchaSolved: false,
      orderPopupText: null,
      validCodes: [],
      discountCodeError: null,
    },
    formStyle: {
      showLoginPopup: false,
      showRegisterInputs: false,
      showDifferentAddressInputs: false,
      showDiscountCode: false,
      showOrderPopup: false,
    }, 
    formErrors: {
      emailError: '',
      passwordError: null,
      plainPasswordError: null,
      nameError: '',
      surnameError: '',
      addressError: '',
      postalCodeError: '',
      cityError: '',
      phoneError: '',
      shippingAddressError: null,
      shippingCityError: null,
      shippingPostalCodeError: null,
      shippingMethodError: '',
      paymentMethodError: '',
      termsAcceptError: '',
    },
    regexRules: {
      emailRegex: /^[^@\s]+@[^@\s]+\.[^@\s]+$/,
      passwordRegex: /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/,
      onlyLettersRegex: /^[A-Z][a-z]*$/,
      bigFirstLetter: /^[A-Z].*$/,
      postalCodeRegex: /^\d{2}-\d{3}$/,
      phoneRegex: /^\+?\d{7,15}$/,
    },
    orderData: {
      termsAccept: false,
      shippingMethod: null,
      paymentMethod: null,
      comment: null,
      discountCode: null,
      discountCodeId: null,
      discountPercentage: null,
      user: {
        email: null,
        password: null,
        plainPassword: null,
        name: null,
        surname: null,
        country: 'Polska',
        address: null,
        postalCode: null,
        city: null,
        phone: null,
        newsletter: null,
        shippingAddress: null,
        shippingCity: null,
        shippingPostalCode: null,
      }
    },
  }),

});
